-- Auto-generated by scripts/dump-schema.sh — do not edit by hand.
-- Regenerated automatically by 'make migrate' and 'make migrate-down'.

--
-- PostgreSQL database dump
--

\restrict valoraschemadump

-- Dumped from database version 17.10 (Debian 17.10-1.pgdg13+1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: btree_gist; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA public;


--
-- Name: EXTENSION btree_gist; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION btree_gist IS 'support for indexing common datatypes in GiST';


SET default_table_access_method = heap;

--
-- Name: facts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.facts (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    concept_id bigint NOT NULL,
    line_item_id bigint,
    period_start date NOT NULL,
    period_end date NOT NULL,
    period_type text NOT NULL,
    basis text NOT NULL,
    value numeric NOT NULL,
    currency text NOT NULL,
    scale text NOT NULL,
    document_id bigint NOT NULL,
    page integer NOT NULL,
    bbox jsonb NOT NULL,
    confidence numeric,
    verified_by bigint,
    verified_at timestamp with time zone,
    extraction_run_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    knowledge_period tstzrange NOT NULL,
    CONSTRAINT facts_basis_check CHECK ((basis = ANY (ARRAY['as_reported'::text, 'restated'::text]))),
    CONSTRAINT facts_bbox_check CHECK (((bbox ?& ARRAY['x0'::text, 'y0'::text, 'x1'::text, 'y1'::text]) AND (((bbox ->> 'x0'::text))::numeric >= (0)::numeric) AND (((bbox ->> 'x0'::text))::numeric <= (1)::numeric) AND (((bbox ->> 'y0'::text))::numeric >= (0)::numeric) AND (((bbox ->> 'y0'::text))::numeric <= (1)::numeric) AND (((bbox ->> 'x1'::text))::numeric >= (0)::numeric) AND (((bbox ->> 'x1'::text))::numeric <= (1)::numeric) AND (((bbox ->> 'y1'::text))::numeric >= (0)::numeric) AND (((bbox ->> 'y1'::text))::numeric <= (1)::numeric) AND (((bbox ->> 'x0'::text))::numeric < ((bbox ->> 'x1'::text))::numeric) AND (((bbox ->> 'y0'::text))::numeric < ((bbox ->> 'y1'::text))::numeric))),
    CONSTRAINT facts_confidence_check CHECK (((confidence >= (0)::numeric) AND (confidence <= (1)::numeric))),
    CONSTRAINT facts_currency_check CHECK ((currency ~ '^[A-Z]{3}$'::text)),
    CONSTRAINT facts_knowledge_period_shape CHECK (((NOT isempty(knowledge_period)) AND (NOT lower_inf(knowledge_period)) AND lower_inc(knowledge_period) AND (NOT upper_inc(knowledge_period)))),
    CONSTRAINT facts_page_check CHECK ((page > 0)),
    CONSTRAINT facts_period_end_after_period_start CHECK ((period_end > period_start)),
    CONSTRAINT facts_period_type_check CHECK ((period_type = ANY (ARRAY['FY'::text, 'H1'::text]))),
    CONSTRAINT facts_scale_check CHECK ((scale = ANY (ARRAY['units'::text, 'thousands'::text, 'millions'::text]))),
    CONSTRAINT facts_verification_consistency CHECK (((verified_by IS NULL) = (verified_at IS NULL)))
);


--
-- Name: COLUMN facts.line_item_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.facts.line_item_id IS 'Which as-reported line item (company_line_items) produced this fact, so the exact company terminology used survives even as it changes across a filing history. NULL indicates a derived fact with no printed source line — not a data-quality gap.';


--
-- Name: COLUMN facts.basis; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.facts.basis IS 'as_reported: value as originally disclosed, in the filing that first reported this period. restated: a later filing''s revised figure for a past period. The two coexist as parallel rows for the same period — not versions of each other.';


--
-- Name: COLUMN facts.value; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.facts.value IS 'Canonical value, already normalised to actual units regardless of how the source document presented it (M4.15). Never multiply this by scale — scale is provenance only, describing how the source printed it, not a multiplier to apply.';


--
-- Name: COLUMN facts.scale; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.facts.scale IS 'Provenance: the scale the SOURCE document used to print this value (e.g. a statement header reading "R''000"). value is already canonical at the actual-units scale; this column is never consumed to compute it.';


--
-- Name: COLUMN facts.bbox; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.facts.bbox IS 'JSON object {x0,y0,x1,y1}: bounding box of the value on its source page, normalised to [0,1] of page width/height, origin top-left (image/screen convention, not raw PDF bottom-left-origin points). (x0,y0) top-left corner, (x1,y1) bottom-right.';


--
-- Name: COLUMN facts.confidence; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.facts.confidence IS 'Automated extraction confidence in [0,1]. NULL means no automated score exists (e.g. a hand-typed golden-dataset fact, M2), not zero confidence.';


--
-- Name: COLUMN facts.verified_by; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.facts.verified_by IS 'Will reference a users/reviewers table once it exists (M7) — no FK yet. NULL means not yet human-verified.';


--
-- Name: COLUMN facts.extraction_run_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.facts.extraction_run_id IS 'References the extraction_runs table once it exists (M6.3) — no FK yet. NULL for facts with no extraction run behind them (e.g. hand-typed golden-dataset facts, M2).';


--
-- Name: COLUMN facts.knowledge_period; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.facts.knowledge_period IS 'The period during which Valora believed this fact (bitemporal axis, distinct from period_start/period_end which describe the fiscal period the fact is ABOUT). Bounds are always [lower, upper): lower inclusive, upper exclusive, so a closed-then-reopened pair of ranges at the same instant abut without gap or overlap. Unbounded upper (e.g. tstzrange(t, NULL)) means "believed from t, still currently believed" — this is how "current" is represented; there is no separate flag for it. No column default: the correct lower bound is the actual instant belief began (extraction completion, verification, or publish time, depending on the writer), which Postgres''s now() at INSERT time does not reliably represent — a wrong default here would be silently wrong, not loudly wrong, so every writer must compute and supply it explicitly.';


--
-- Name: facts_as_of(timestamp with time zone); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.facts_as_of(p_as_of timestamp with time zone DEFAULT now()) RETURNS SETOF public.facts
    LANGUAGE sql STABLE
    AS $$
  select *
  from facts
  where knowledge_period @> p_as_of
$$;


--
-- Name: FUNCTION facts_as_of(p_as_of timestamp with time zone); Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON FUNCTION public.facts_as_of(p_as_of timestamp with time zone) IS 'Canonical as_of query (spec §7, GET /v1/facts?as_of=). Returns every fact row Valora believed as of the given instant (default now() — the current view). Uses knowledge_period''s containment operator directly, which already respects the [lower, upper) bound convention decided in M1.8: an as_of exactly at a restatement boundary instant t2 returns the NEW row, since [t1,t2) excludes t2 while [t2,t3) includes it. M9.3 (GET /v1/facts?as_of=) MUST call this function rather than reimplement the containment check in TypeScript — that is the entire reason it exists as a database function rather than a query embedded in either language. Company/concept/period/basis filtering belongs on top of this function''s output; it resolves only the bitemporal axis.';


--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;


--
-- Name: companies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.companies (
    id bigint NOT NULL,
    name text NOT NULL,
    jse_code text NOT NULL,
    sector text,
    archetype text NOT NULL,
    fye_month smallint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT companies_archetype_check CHECK ((archetype = ANY (ARRAY['retail'::text, 'bank'::text]))),
    CONSTRAINT companies_fye_month_check CHECK (((fye_month >= 1) AND (fye_month <= 12)))
);


--
-- Name: companies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.companies ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.companies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_line_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_line_items (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    as_reported_label text NOT NULL,
    mapping_status text DEFAULT 'unreviewed'::text NOT NULL,
    concept_id bigint,
    first_seen_doc_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT company_line_items_mapping_status_check CHECK ((mapping_status = ANY (ARRAY['unreviewed'::text, 'mapped'::text, 'unmapped'::text]))),
    CONSTRAINT company_line_items_mapping_status_consistency CHECK ((((mapping_status = 'mapped'::text) AND (concept_id IS NOT NULL)) OR ((mapping_status = ANY (ARRAY['unreviewed'::text, 'unmapped'::text])) AND (concept_id IS NULL))))
);


--
-- Name: COLUMN company_line_items.as_reported_label; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_line_items.as_reported_label IS 'Verbatim as printed by the company. Never normalised or destroyed. NOT unique per (company_id, as_reported_label): the same label (e.g. "Total") legitimately recurs across different statements/notes for one company, and no column here disambiguates those occurrences — see PROGRESS.md / migration history for M1.6.';


--
-- Name: COLUMN company_line_items.mapping_status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_line_items.mapping_status IS 'unreviewed: not yet looked at (concept_id NULL). mapped: standard concept confirmed (concept_id set). unmapped: explicitly reviewed and decided to have no standard equivalent (concept_id NULL, but deliberately so, not by default).';


--
-- Name: company_line_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company_line_items ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.company_line_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: concepts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.concepts (
    id bigint NOT NULL,
    code text NOT NULL,
    label text NOT NULL,
    archetype_set text[] NOT NULL,
    statement text,
    sign_convention text NOT NULL,
    unit_type text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT concepts_archetype_set_check CHECK (((cardinality(archetype_set) > 0) AND (archetype_set <@ ARRAY['retail'::text, 'bank'::text]))),
    CONSTRAINT concepts_code_check CHECK ((code ~ '^[a-z][a-z0-9_]*$'::text)),
    CONSTRAINT concepts_sign_convention_check CHECK ((sign_convention = ANY (ARRAY['natural'::text, 'signed'::text]))),
    CONSTRAINT concepts_statement_check CHECK ((statement = ANY (ARRAY['income_statement'::text, 'balance_sheet'::text, 'cash_flow'::text]))),
    CONSTRAINT concepts_unit_type_check CHECK ((unit_type = ANY (ARRAY['currency'::text, 'currency_per_share'::text, 'count'::text, 'percentage'::text, 'ratio'::text, 'density'::text])))
);


--
-- Name: COLUMN concepts.statement; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.concepts.statement IS 'Which primary financial statement this concept belongs to. NULL means it does not belong to one of the three (e.g. a note-level or operating-KPI concept such as store count or trading space).';


--
-- Name: COLUMN concepts.sign_convention; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.concepts.sign_convention IS 'How this concept''s value is signed in canonical storage. ''natural'': always a positive magnitude regardless of whether the concept adds or subtracts in its parent total (e.g. cost_of_sales stored as 50000; consuming code must apply the correct sign based on the concept''s role). ''signed'': stored with the sign it contributes to its parent total (e.g. cost_of_sales stored as -50000, so gross_profit = revenue + cost_of_sales works by plain summation).';


--
-- Name: COLUMN concepts.unit_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.concepts.unit_type IS 'The unit family this concept''s value is denominated in: currency (absolute monetary value), currency_per_share (e.g. HEPS, NAV per share), count (e.g. store count, headcount), percentage (e.g. like-for-like growth, margins), ratio (non-percentage ratios, e.g. gearing), density (area-denominated measures, e.g. trading density as currency per square metre).';


--
-- Name: concepts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.concepts ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.concepts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documents (
    id bigint NOT NULL,
    s3_key text NOT NULL,
    sha256 text NOT NULL,
    ingested_at timestamp with time zone DEFAULT now() NOT NULL,
    page_count integer,
    company_id bigint,
    doc_type text,
    fiscal_period text,
    published_at date,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT documents_doc_type_check CHECK ((doc_type = ANY (ARRAY['annual_report'::text, 'interim_results'::text, 'results_presentation'::text, 'excel_databook'::text]))),
    CONSTRAINT documents_sha256_check CHECK ((sha256 ~ '^[0-9a-f]{64}$'::text))
);


--
-- Name: COLUMN documents.ingested_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.documents.ingested_at IS 'The exact instant Valora first stored this document. Not the same as published_at.';


--
-- Name: COLUMN documents.page_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.documents.page_count IS 'NULL means the document has not been successfully parsed yet (e.g. corrupt file, truncated download, encrypted PDF) — not that it has zero pages.';


--
-- Name: COLUMN documents.fiscal_period; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.documents.fiscal_period IS 'Human-readable label for the period the document AS A WHOLE covers (e.g. FY2025, H1 2025). Distinct from facts.period_start/period_end/period_type, which give exact per-fact period boundaries since one document can contain comparative-period facts.';


--
-- Name: COLUMN documents.published_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.documents.published_at IS 'The date the COMPANY published this filing (day precision only, from the document itself). Not the same as ingested_at.';


--
-- Name: documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documents ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: facts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.facts ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.facts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: instruments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.instruments (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    isin text NOT NULL,
    share_code text NOT NULL,
    class text NOT NULL,
    listed_from date NOT NULL,
    listed_to date,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT instruments_class_check CHECK ((class = ANY (ARRAY['ordinary'::text, 'n_ordinary'::text, 'preference'::text]))),
    CONSTRAINT instruments_listed_to_after_listed_from CHECK (((listed_to IS NULL) OR (listed_to > listed_from)))
);


--
-- Name: COLUMN instruments.listed_to; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.instruments.listed_to IS 'NULL means the instrument is currently listed.';


--
-- Name: instruments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.instruments ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.instruments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying NOT NULL
);


--
-- Name: companies companies_jse_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_jse_code_key UNIQUE (jse_code);


--
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);


--
-- Name: company_line_items company_line_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_line_items
    ADD CONSTRAINT company_line_items_pkey PRIMARY KEY (id);


--
-- Name: concepts concepts_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.concepts
    ADD CONSTRAINT concepts_code_key UNIQUE (code);


--
-- Name: concepts concepts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.concepts
    ADD CONSTRAINT concepts_pkey PRIMARY KEY (id);


--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);


--
-- Name: documents documents_s3_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_s3_key_key UNIQUE (s3_key);


--
-- Name: documents documents_sha256_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_sha256_key UNIQUE (sha256);


--
-- Name: facts facts_no_overlapping_knowledge_periods; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facts
    ADD CONSTRAINT facts_no_overlapping_knowledge_periods EXCLUDE USING gist (company_id WITH =, concept_id WITH =, period_start WITH =, period_type WITH =, basis WITH =, knowledge_period WITH &&) DEFERRABLE;


--
-- Name: facts facts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facts
    ADD CONSTRAINT facts_pkey PRIMARY KEY (id);


--
-- Name: instruments instruments_isin_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instruments
    ADD CONSTRAINT instruments_isin_key UNIQUE (isin);


--
-- Name: instruments instruments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instruments
    ADD CONSTRAINT instruments_pkey PRIMARY KEY (id);


--
-- Name: instruments instruments_share_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instruments
    ADD CONSTRAINT instruments_share_code_key UNIQUE (share_code);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: company_line_items_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX company_line_items_company_id_idx ON public.company_line_items USING btree (company_id);


--
-- Name: company_line_items_concept_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX company_line_items_concept_id_idx ON public.company_line_items USING btree (concept_id);


--
-- Name: company_line_items_unreviewed_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX company_line_items_unreviewed_idx ON public.company_line_items USING btree (company_id) WHERE (mapping_status = 'unreviewed'::text);


--
-- Name: concepts_archetype_set_gin_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX concepts_archetype_set_gin_idx ON public.concepts USING gin (archetype_set);


--
-- Name: documents_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX documents_company_id_idx ON public.documents USING btree (company_id);


--
-- Name: facts_company_concept_period_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX facts_company_concept_period_idx ON public.facts USING btree (company_id, concept_id, period_start);


--
-- Name: instruments_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX instruments_company_id_idx ON public.instruments USING btree (company_id);


--
-- Name: companies companies_set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER companies_set_updated_at BEFORE UPDATE ON public.companies FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: company_line_items company_line_items_set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER company_line_items_set_updated_at BEFORE UPDATE ON public.company_line_items FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: concepts concepts_set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER concepts_set_updated_at BEFORE UPDATE ON public.concepts FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: documents documents_set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER documents_set_updated_at BEFORE UPDATE ON public.documents FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: facts facts_set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER facts_set_updated_at BEFORE UPDATE ON public.facts FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: instruments instruments_set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER instruments_set_updated_at BEFORE UPDATE ON public.instruments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: company_line_items company_line_items_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_line_items
    ADD CONSTRAINT company_line_items_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE RESTRICT;


--
-- Name: company_line_items company_line_items_concept_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_line_items
    ADD CONSTRAINT company_line_items_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id) ON DELETE RESTRICT;


--
-- Name: company_line_items company_line_items_first_seen_doc_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_line_items
    ADD CONSTRAINT company_line_items_first_seen_doc_id_fkey FOREIGN KEY (first_seen_doc_id) REFERENCES public.documents(id) ON DELETE RESTRICT;


--
-- Name: documents documents_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE RESTRICT;


--
-- Name: facts facts_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facts
    ADD CONSTRAINT facts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE RESTRICT;


--
-- Name: facts facts_concept_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facts
    ADD CONSTRAINT facts_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id) ON DELETE RESTRICT;


--
-- Name: facts facts_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facts
    ADD CONSTRAINT facts_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE RESTRICT;


--
-- Name: facts facts_line_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facts
    ADD CONSTRAINT facts_line_item_id_fkey FOREIGN KEY (line_item_id) REFERENCES public.company_line_items(id) ON DELETE RESTRICT;


--
-- Name: instruments instruments_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instruments
    ADD CONSTRAINT instruments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict valoraschemadump


--
-- PostgreSQL database dump
--

\restrict valoraschemadump

-- Dumped from database version 17.10 (Debian 17.10-1.pgdg13+1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: schema_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.schema_migrations (version) VALUES ('20260802184933');
INSERT INTO public.schema_migrations (version) VALUES ('20260802190738');
INSERT INTO public.schema_migrations (version) VALUES ('20260802193015');
INSERT INTO public.schema_migrations (version) VALUES ('20260805142451');
INSERT INTO public.schema_migrations (version) VALUES ('20260805144105');
INSERT INTO public.schema_migrations (version) VALUES ('20260805145921');
INSERT INTO public.schema_migrations (version) VALUES ('20260805152208');
INSERT INTO public.schema_migrations (version) VALUES ('20260805184045');


--
-- PostgreSQL database dump complete
--

\unrestrict valoraschemadump

