-- Auto-generated by scripts/dump-schema.sh — do not edit by hand.
-- Regenerated automatically by 'make migrate' and 'make migrate-down'.

--
-- PostgreSQL database dump
--

\restrict valoraschemadump

-- Dumped from database version 17.10 (Debian 17.10-1.pgdg13+1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;


SET default_table_access_method = heap;

--
-- Name: companies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.companies (
    id bigint NOT NULL,
    name text NOT NULL,
    jse_code text NOT NULL,
    sector text,
    archetype text NOT NULL,
    fye_month smallint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT companies_archetype_check CHECK ((archetype = ANY (ARRAY['retail'::text, 'bank'::text]))),
    CONSTRAINT companies_fye_month_check CHECK (((fye_month >= 1) AND (fye_month <= 12)))
);


--
-- Name: companies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.companies ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.companies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documents (
    id bigint NOT NULL,
    s3_key text NOT NULL,
    sha256 text NOT NULL,
    ingested_at timestamp with time zone DEFAULT now() NOT NULL,
    page_count integer,
    company_id bigint,
    doc_type text,
    fiscal_period text,
    published_at date,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT documents_doc_type_check CHECK ((doc_type = ANY (ARRAY['annual_report'::text, 'interim_results'::text, 'results_presentation'::text, 'excel_databook'::text]))),
    CONSTRAINT documents_sha256_check CHECK ((sha256 ~ '^[0-9a-f]{64}$'::text))
);


--
-- Name: COLUMN documents.ingested_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.documents.ingested_at IS 'The exact instant Valora first stored this document. Not the same as published_at.';


--
-- Name: COLUMN documents.page_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.documents.page_count IS 'NULL means the document has not been successfully parsed yet (e.g. corrupt file, truncated download, encrypted PDF) — not that it has zero pages.';


--
-- Name: COLUMN documents.fiscal_period; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.documents.fiscal_period IS 'Human-readable label for the period the document AS A WHOLE covers (e.g. FY2025, H1 2025). Distinct from facts.period_start/period_end/period_type, which give exact per-fact period boundaries since one document can contain comparative-period facts.';


--
-- Name: COLUMN documents.published_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.documents.published_at IS 'The date the COMPANY published this filing (day precision only, from the document itself). Not the same as ingested_at.';


--
-- Name: documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documents ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: instruments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.instruments (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    isin text NOT NULL,
    share_code text NOT NULL,
    class text NOT NULL,
    listed_from date NOT NULL,
    listed_to date,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT instruments_class_check CHECK ((class = ANY (ARRAY['ordinary'::text, 'n_ordinary'::text, 'preference'::text]))),
    CONSTRAINT instruments_listed_to_after_listed_from CHECK (((listed_to IS NULL) OR (listed_to > listed_from)))
);


--
-- Name: COLUMN instruments.listed_to; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.instruments.listed_to IS 'NULL means the instrument is currently listed.';


--
-- Name: instruments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.instruments ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.instruments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying NOT NULL
);


--
-- Name: companies companies_jse_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_jse_code_key UNIQUE (jse_code);


--
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);


--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);


--
-- Name: documents documents_s3_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_s3_key_key UNIQUE (s3_key);


--
-- Name: documents documents_sha256_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_sha256_key UNIQUE (sha256);


--
-- Name: instruments instruments_isin_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instruments
    ADD CONSTRAINT instruments_isin_key UNIQUE (isin);


--
-- Name: instruments instruments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instruments
    ADD CONSTRAINT instruments_pkey PRIMARY KEY (id);


--
-- Name: instruments instruments_share_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instruments
    ADD CONSTRAINT instruments_share_code_key UNIQUE (share_code);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: documents_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX documents_company_id_idx ON public.documents USING btree (company_id);


--
-- Name: instruments_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX instruments_company_id_idx ON public.instruments USING btree (company_id);


--
-- Name: companies companies_set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER companies_set_updated_at BEFORE UPDATE ON public.companies FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: documents documents_set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER documents_set_updated_at BEFORE UPDATE ON public.documents FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: instruments instruments_set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER instruments_set_updated_at BEFORE UPDATE ON public.instruments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: documents documents_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE RESTRICT;


--
-- Name: instruments instruments_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instruments
    ADD CONSTRAINT instruments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict valoraschemadump


--
-- PostgreSQL database dump
--

\restrict valoraschemadump

-- Dumped from database version 17.10 (Debian 17.10-1.pgdg13+1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: schema_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.schema_migrations (version) VALUES ('20260802184933');
INSERT INTO public.schema_migrations (version) VALUES ('20260802190738');
INSERT INTO public.schema_migrations (version) VALUES ('20260802193015');


--
-- PostgreSQL database dump complete
--

\unrestrict valoraschemadump

