#!/usr/bin/env bash
# Dumps the current schema (plus schema_migrations rows, so the file records
# which migrations are applied — matching dbmate's own convention) to
# db/schema.sql, deterministically.
#
# Runs pg_dump INSIDE the postgres container via `docker compose exec`,
# resolved by compose SERVICE name rather than a hardcoded container name
# (the same class of bug already fixed in wait-for-healthy.sh). This works
# around a real problem on this machine: the host's pg_dump (16.14) cannot
# dump a PostgreSQL 17.10 server, and installing a matching host client isn't
# currently possible (apt.postgresql.org TLS handshake failures). The
# in-container pg_dump is version-matched to the server by construction.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCHEMA_FILE="${REPO_ROOT}/db/schema.sql"

# Fixed so repeated dumps of an unchanged schema are byte-identical. Recent
# pg_dump wraps output in \restrict/\unrestrict with a randomly generated
# token by default — pinning it removes the single source of spurious diffs.
# Must be alphanumeric only (pg_dump rejects a key containing punctuation).
RESTRICT_KEY="valoraschemadump"

cd "$REPO_ROOT"

if [ -z "$(docker compose ps --status running -q postgres)" ]; then
  echo "ERROR: the 'postgres' compose service is not running. Run 'make dev' first." >&2
  exit 1
fi

pg_dump_in_container() {
  docker compose exec -T -e RESTRICT_KEY="$RESTRICT_KEY" postgres sh -c \
    'pg_dump -U "$POSTGRES_USER" -d "$POSTGRES_DB" --restrict-key="$RESTRICT_KEY" '"$1"
}

{
  echo "-- Auto-generated by scripts/dump-schema.sh — do not edit by hand."
  echo "-- Regenerated automatically by 'make migrate' and 'make migrate-down'."
  echo
  pg_dump_in_container "--schema-only --no-owner --no-privileges --no-tablespaces"
  echo
  pg_dump_in_container "--data-only --no-owner --no-privileges --column-inserts --table=public.schema_migrations"
} > "$SCHEMA_FILE"

echo "Wrote db/schema.sql"
